//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Equipment_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Equipment_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Equipment_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Equipment Info.
        /// </summary>
        internal static string addEditNewEquipment {
            get {
                return ResourceManager.GetString("addEditNewEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ +Add More ].
        /// </summary>
        internal static string addMore {
            get {
                return ResourceManager.GetString("addMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Equipment.
        /// </summary>
        internal static string addNewEquipment {
            get {
                return ResourceManager.GetString("addNewEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Documents &amp; Images.
        /// </summary>
        internal static string addViewDocumentnAndImages {
            get {
                return ResourceManager.GetString("addViewDocumentnAndImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Functional Location.
        /// </summary>
        internal static string addViewFunctionalLoc {
            get {
                return ResourceManager.GetString("addViewFunctionalLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Measuring Points.
        /// </summary>
        internal static string addViewMeasuringPoint {
            get {
                return ResourceManager.GetString("addViewMeasuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Group.
        /// </summary>
        internal static string authorizationGroup {
            get {
                return ResourceManager.GetString("authorizationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Code.
        /// </summary>
        internal static string clearCode {
            get {
                return ResourceManager.GetString("clearCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Search Criteria.
        /// </summary>
        internal static string defineSearchCriteria {
            get {
                return ResourceManager.GetString("defineSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to import model details.
        /// </summary>
        internal static string doubleClicktoImportModelDetails {
            get {
                return ResourceManager.GetString("doubleClicktoImportModelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and upload.
        /// </summary>
        internal static string downloadAndUpload {
            get {
                return ResourceManager.GetString("downloadAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Barcode.
        /// </summary>
        internal static string downloadBarcode {
            get {
                return ResourceManager.GetString("downloadBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Equipment Info.
        /// </summary>
        internal static string downloadExcel {
            get {
                return ResourceManager.GetString("downloadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        internal static string downloadTemplate {
            get {
                return ResourceManager.GetString("downloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Code.
        /// </summary>
        internal static string equipmentCode {
            get {
                return ResourceManager.GetString("equipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Model Information.
        /// </summary>
        internal static string equipmentModelInformation {
            get {
                return ResourceManager.GetString("equipmentModelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        internal static string equipmentName {
            get {
                return ResourceManager.GetString("equipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name/Code.
        /// </summary>
        internal static string equipmentNameOrCode {
            get {
                return ResourceManager.GetString("equipmentNameOrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments.
        /// </summary>
        internal static string equipments {
            get {
                return ResourceManager.GetString("equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code.
        /// </summary>
        internal static string generateCode {
            get {
                return ResourceManager.GetString("generateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload below 5 MB file only.
        /// </summary>
        internal static string imageUploadInstruction {
            get {
                return ResourceManager.GetString("imageUploadInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Date.
        /// </summary>
        internal static string installDate {
            get {
                return ResourceManager.GetString("installDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This equipment is part of .
        /// </summary>
        internal static string linkEquipment {
            get {
                return ResourceManager.GetString("linkEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Resource.
        /// </summary>
        internal static string linkResource {
            get {
                return ResourceManager.GetString("linkResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Information.
        /// </summary>
        internal static string modelInformation {
            get {
                return ResourceManager.GetString("modelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name.
        /// </summary>
        internal static string modelName {
            get {
                return ResourceManager.GetString("modelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string modelNumber {
            get {
                return ResourceManager.GetString("modelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        internal static string purchaseDate {
            get {
                return ResourceManager.GetString("purchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer from model master data.
        /// </summary>
        internal static string referModelMaster {
            get {
                return ResourceManager.GetString("referModelMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string seriesNo {
            get {
                return ResourceManager.GetString("seriesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By :.
        /// </summary>
        internal static string sortBy {
            get {
                return ResourceManager.GetString("sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        internal static string sortByName {
            get {
                return ResourceManager.GetString("sortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Details.
        /// </summary>
        internal static string supportDetails {
            get {
                return ResourceManager.GetString("supportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Email.
        /// </summary>
        internal static string supportEmail {
            get {
                return ResourceManager.GetString("supportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Name.
        /// </summary>
        internal static string supportName {
            get {
                return ResourceManager.GetString("supportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Number.
        /// </summary>
        internal static string supportNumber {
            get {
                return ResourceManager.GetString("supportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Type.
        /// </summary>
        internal static string supportType {
            get {
                return ResourceManager.GetString("supportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        internal static string updatedOn {
            get {
                return ResourceManager.GetString("updatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Equipment Info.
        /// </summary>
        internal static string uploadExcel {
            get {
                return ResourceManager.GetString("uploadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Details.
        /// </summary>
        internal static string warrantyDetails {
            get {
                return ResourceManager.GetString("warrantyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Expire.
        /// </summary>
        internal static string warrantyExpire {
            get {
                return ResourceManager.GetString("warrantyExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Number.
        /// </summary>
        internal static string warrantyNumber {
            get {
                return ResourceManager.GetString("warrantyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Start.
        /// </summary>
        internal static string warrantyStart {
            get {
                return ResourceManager.GetString("warrantyStart", resourceCulture);
            }
        }
    }
}
