//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EquipmentModel_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquipmentModel_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EquipmentModel_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Equipment Model Info.
        /// </summary>
        internal static string addEditEquipmentModel {
            get {
                return ResourceManager.GetString("addEditEquipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string addNew {
            get {
                return ResourceManager.GetString("addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Equipment Model.
        /// </summary>
        internal static string addNewEquipmentModel {
            get {
                return ResourceManager.GetString("addNewEquipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Documents &amp; Images.
        /// </summary>
        internal static string addViewDocumentsAndImages {
            get {
                return ResourceManager.GetString("addViewDocumentsAndImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Measuring Points.
        /// </summary>
        internal static string addViewMeasuringPoint {
            get {
                return ResourceManager.GetString("addViewMeasuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close .
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Upload.
        /// </summary>
        internal static string downloadAndUpload {
            get {
                return ResourceManager.GetString("downloadAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Excel.
        /// </summary>
        internal static string downloadExcel {
            get {
                return ResourceManager.GetString("downloadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        internal static string downloadTemplate {
            get {
                return ResourceManager.GetString("downloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Model.
        /// </summary>
        internal static string equipmentModel {
            get {
                return ResourceManager.GetString("equipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload below 5 MB file only.
        /// </summary>
        internal static string imageUploadInstruction {
            get {
                return ResourceManager.GetString("imageUploadInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Equipment Model .
        /// </summary>
        internal static string listOfEquipmentModel {
            get {
                return ResourceManager.GetString("listOfEquipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string modelClass {
            get {
                return ResourceManager.GetString("modelClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name.
        /// </summary>
        internal static string modelName {
            get {
                return ResourceManager.GetString("modelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string modelType {
            get {
                return ResourceManager.GetString("modelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model/Version No.
        /// </summary>
        internal static string model_versionNo {
            get {
                return ResourceManager.GetString("model_versionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Add More.
        /// </summary>
        internal static string saveAndAddMore {
            get {
                return ResourceManager.GetString("saveAndAddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search model name.
        /// </summary>
        internal static string searchModelName {
            get {
                return ResourceManager.GetString("searchModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        internal static string sortByName {
            get {
                return ResourceManager.GetString("sortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Equipment Models.
        /// </summary>
        internal static string uplaodEquipmentModel {
            get {
                return ResourceManager.GetString("uplaodEquipmentModel", resourceCulture);
            }
        }
    }
}
