//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FunctionalLocation_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FunctionalLocation_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FunctionalLocation_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Functional Location Info.
        /// </summary>
        internal static string addEditFunctionalLocation {
            get {
                return ResourceManager.GetString("addEditFunctionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Functional Location.
        /// </summary>
        internal static string addNewFunctionalLocation {
            get {
                return ResourceManager.GetString("addNewFunctionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Equipments.
        /// </summary>
        internal static string addViewEquipments {
            get {
                return ResourceManager.GetString("addViewEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Measuring Points.
        /// </summary>
        internal static string addViewMeasuringPoints {
            get {
                return ResourceManager.GetString("addViewMeasuringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Group.
        /// </summary>
        internal static string authorizationGroup {
            get {
                return ResourceManager.GetString("authorizationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Code.
        /// </summary>
        internal static string clearCode {
            get {
                return ResourceManager.GetString("clearCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Search Criteria.
        /// </summary>
        internal static string defineSearchCriteria {
            get {
                return ResourceManager.GetString("defineSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Upload.
        /// </summary>
        internal static string downloadAndUpload {
            get {
                return ResourceManager.GetString("downloadAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Barcode.
        /// </summary>
        internal static string downloadBarcode {
            get {
                return ResourceManager.GetString("downloadBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Functional Location Info.
        /// </summary>
        internal static string downloadFunctionalLocInfo {
            get {
                return ResourceManager.GetString("downloadFunctionalLocInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        internal static string downloadTemplate {
            get {
                return ResourceManager.GetString("downloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments.
        /// </summary>
        internal static string equipments {
            get {
                return ResourceManager.GetString("equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location Code.
        /// </summary>
        internal static string functionalLocationCode {
            get {
                return ResourceManager.GetString("functionalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location Name.
        /// </summary>
        internal static string functionalLocName {
            get {
                return ResourceManager.GetString("functionalLocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code.
        /// </summary>
        internal static string generateCode {
            get {
                return ResourceManager.GetString("generateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload below 5 MB file only.
        /// </summary>
        internal static string imageUploadInstruction {
            get {
                return ResourceManager.GetString("imageUploadInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        internal static string locationName {
            get {
                return ResourceManager.GetString("locationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Functional Loc. is part of.
        /// </summary>
        internal static string parentFLocMsg {
            get {
                return ResourceManager.GetString("parentFLocMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Add More.
        /// </summary>
        internal static string saveAndAddMore {
            get {
                return ResourceManager.GetString("saveAndAddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By :.
        /// </summary>
        internal static string sortBy {
            get {
                return ResourceManager.GetString("sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        internal static string sortByName {
            get {
                return ResourceManager.GetString("sortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        internal static string updatedOn {
            get {
                return ResourceManager.GetString("updatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Functional Location Info.
        /// </summary>
        internal static string uploadFLocation {
            get {
                return ResourceManager.GetString("uploadFLocation", resourceCulture);
            }
        }
    }
}
