//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaintenanceFeatures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceFeatures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MaintenanceFeatures", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENT_MODELS.
        /// </summary>
        internal static string equipmentModels {
            get {
                return ResourceManager.GetString("equipmentModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUIPMENTS.
        /// </summary>
        internal static string equipments {
            get {
                return ResourceManager.GetString("equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUNCTIONAL_LOCATION.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE_CHECKLIST.
        /// </summary>
        internal static string ManageChecklist {
            get {
                return ResourceManager.GetString("ManageChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE_NOTIFICATION.
        /// </summary>
        internal static string manageNotification {
            get {
                return ResourceManager.GetString("manageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE_SCHEDULE.
        /// </summary>
        internal static string ManageSchedule {
            get {
                return ResourceManager.GetString("ManageSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE_WORKORDER.
        /// </summary>
        internal static string ManageWorkOrder {
            get {
                return ResourceManager.GetString("ManageWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEASURING_POINTS.
        /// </summary>
        internal static string measuringPoints {
            get {
                return ResourceManager.GetString("measuringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEWMEASPNTREADINGS.
        /// </summary>
        internal static string viewMeasuringPointReadings {
            get {
                return ResourceManager.GetString("viewMeasuringPointReadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKORDER_DAYVIEW.
        /// </summary>
        internal static string workOrderDayView {
            get {
                return ResourceManager.GetString("workOrderDayView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKORDER_ORDERVIEW.
        /// </summary>
        internal static string workOrderOrderView {
            get {
                return ResourceManager.GetString("workOrderOrderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKORDER_RESOURCEVIEW.
        /// </summary>
        internal static string workOrderResourceView {
            get {
                return ResourceManager.GetString("workOrderResourceView", resourceCulture);
            }
        }
    }
}
