//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaintenanceIndex_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceIndex_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MaintenanceIndex_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Email Templates.
        /// </summary>
        internal static string configureEmailTemplates {
            get {
                return ResourceManager.GetString("configureEmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Locations &amp; Equipment.
        /// </summary>
        internal static string configureLocationAndEquipment {
            get {
                return ResourceManager.GetString("configureLocationAndEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Spare Parts.
        /// </summary>
        internal static string configureSpareParts {
            get {
                return ResourceManager.GetString("configureSpareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Tools.
        /// </summary>
        internal static string configureTools {
            get {
                return ResourceManager.GetString("configureTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Work Group.
        /// </summary>
        internal static string configureWorkGroup {
            get {
                return ResourceManager.GetString("configureWorkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant Email Templates with Email type,Information can be configured along with Email IDs.
        /// </summary>
        internal static string emailTemplatesDescription {
            get {
                return ResourceManager.GetString("emailTemplatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to Configure Locations, Equipment, Measuring Points etc.
        /// </summary>
        internal static string LocationAndEquipmentDescription {
            get {
                return ResourceManager.GetString("LocationAndEquipmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Check List.
        /// </summary>
        internal static string manageCheckList {
            get {
                return ResourceManager.GetString("manageCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage check list.
        /// </summary>
        internal static string manageChecklistDesc {
            get {
                return ResourceManager.GetString("manageChecklistDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Notifications.
        /// </summary>
        internal static string manageNotification {
            get {
                return ResourceManager.GetString("manageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage notifications, convert notifications to work orders..
        /// </summary>
        internal static string manageNotificationDescription {
            get {
                return ResourceManager.GetString("manageNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to view calendar of work orders.
        /// </summary>
        internal static string manageOrderCalendarDescription {
            get {
                return ResourceManager.GetString("manageOrderCalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Preventive Maintenance Schedule.
        /// </summary>
        internal static string managePreventiveMaintenanceSchedule {
            get {
                return ResourceManager.GetString("managePreventiveMaintenanceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to schedule preventive maintenance activity.
        /// </summary>
        internal static string manageScheduleDesc {
            get {
                return ResourceManager.GetString("manageScheduleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage SOP.
        /// </summary>
        internal static string manageTaskGroup {
            get {
                return ResourceManager.GetString("manageTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage maintenance work orders.
        /// </summary>
        internal static string manageWorkOrderDesc {
            get {
                return ResourceManager.GetString("manageWorkOrderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Work Orders.
        /// </summary>
        internal static string manageWorkOrders {
            get {
                return ResourceManager.GetString("manageWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have authorization to access this feature..
        /// </summary>
        internal static string noPermission {
            get {
                return ResourceManager.GetString("noPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Data.
        /// </summary>
        internal static string setupData {
            get {
                return ResourceManager.GetString("setupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option for configure master data.
        /// </summary>
        internal static string setupDataDescription {
            get {
                return ResourceManager.GetString("setupDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        internal static string sorry {
            get {
                return ResourceManager.GetString("sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to setup spare parts materials.
        /// </summary>
        internal static string sparePartsDescription {
            get {
                return ResourceManager.GetString("sparePartsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to group set of commonly used tasks or SOP to be followed during maintenance work.
        /// </summary>
        internal static string taskGroupDescription {
            get {
                return ResourceManager.GetString("taskGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to configure tools (pictorial image) used during maintenance work.
        /// </summary>
        internal static string toolsDescription {
            get {
                return ResourceManager.GetString("toolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to view equipment details.
        /// </summary>
        internal static string viewEquipmentDetails {
            get {
                return ResourceManager.GetString("viewEquipmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to create work groups, add people to work group and set up notification preference.
        /// </summary>
        internal static string workGroupDescription {
            get {
                return ResourceManager.GetString("workGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Calendar.
        /// </summary>
        internal static string workOrderCalendar {
            get {
                return ResourceManager.GetString("workOrderCalendar", resourceCulture);
            }
        }
    }
}
