//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaintenancePageID_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenancePageID_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MaintenancePageID_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10005.
        /// </summary>
        internal static string configureTaskGroup {
            get {
                return ResourceManager.GetString("configureTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10007.
        /// </summary>
        internal static string configureTools {
            get {
                return ResourceManager.GetString("configureTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10019.
        /// </summary>
        internal static string Configure_EmailTemplates {
            get {
                return ResourceManager.GetString("Configure_EmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10003.
        /// </summary>
        internal static string Configure_Equipments {
            get {
                return ResourceManager.GetString("Configure_Equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10002.
        /// </summary>
        internal static string Configure_Equipment_Models {
            get {
                return ResourceManager.GetString("Configure_Equipment_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001.
        /// </summary>
        internal static string Configure_Functional_Loc {
            get {
                return ResourceManager.GetString("Configure_Functional_Loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10014.
        /// </summary>
        internal static string Configure_Maintenance_Type {
            get {
                return ResourceManager.GetString("Configure_Maintenance_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10004.
        /// </summary>
        internal static string Configure_Measuring_Point {
            get {
                return ResourceManager.GetString("Configure_Measuring_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10015.
        /// </summary>
        internal static string Configure_SpareParts {
            get {
                return ResourceManager.GetString("Configure_SpareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10008.
        /// </summary>
        internal static string Configure_WorkGroup {
            get {
                return ResourceManager.GetString("Configure_WorkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10020.
        /// </summary>
        internal static string MaintenanceReports {
            get {
                return ResourceManager.GetString("MaintenanceReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10011.
        /// </summary>
        internal static string ManageChecklist {
            get {
                return ResourceManager.GetString("ManageChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10016.
        /// </summary>
        internal static string ManageNotification {
            get {
                return ResourceManager.GetString("ManageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10009.
        /// </summary>
        internal static string ManagePreventiveMaintenanceSchedule {
            get {
                return ResourceManager.GetString("ManagePreventiveMaintenanceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10010.
        /// </summary>
        internal static string ManageWorkOrder {
            get {
                return ResourceManager.GetString("ManageWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10018.
        /// </summary>
        internal static string Manage_Release {
            get {
                return ResourceManager.GetString("Manage_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 449 .
        /// </summary>
        internal static string ShareUserView {
            get {
                return ResourceManager.GetString("ShareUserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10006.
        /// </summary>
        internal static string taskGroupApprove {
            get {
                return ResourceManager.GetString("taskGroupApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10017.
        /// </summary>
        internal static string ViewEquipment {
            get {
                return ResourceManager.GetString("ViewEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10013.
        /// </summary>
        internal static string ViewWorkOrderInfo {
            get {
                return ResourceManager.GetString("ViewWorkOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10012.
        /// </summary>
        internal static string WorkOrderCalendar {
            get {
                return ResourceManager.GetString("WorkOrderCalendar", resourceCulture);
            }
        }
    }
}
