//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaintenanceSchedule_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceSchedule_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MaintenanceSchedule_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Parameters.
        /// </summary>
        internal static string actionParameter {
            get {
                return ResourceManager.GetString("actionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attachments.
        /// </summary>
        internal static string addAttachment {
            get {
                return ResourceManager.GetString("addAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basic Information.
        /// </summary>
        internal static string addBasicInformation {
            get {
                return ResourceManager.GetString("addBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Maintenance Type.
        /// </summary>
        internal static string addEditMaintType {
            get {
                return ResourceManager.GetString("addEditMaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Instructions Manually.
        /// </summary>
        internal static string addInstructionManually {
            get {
                return ResourceManager.GetString("addInstructionManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Maintenance Work Order.
        /// </summary>
        internal static string addMaintWorkOrder {
            get {
                return ResourceManager.GetString("addMaintWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Add More ].
        /// </summary>
        internal static string addMore {
            get {
                return ResourceManager.GetString("addMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Spare Parts Information.
        /// </summary>
        internal static string addSparePartInformation {
            get {
                return ResourceManager.GetString("addSparePartInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add work instructions to maintenance work.
        /// </summary>
        internal static string addWorkInstrToMaintWork {
            get {
                return ResourceManager.GetString("addWorkInstrToMaintWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        internal static string assignWorkGroup {
            get {
                return ResourceManager.GetString("assignWorkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string attachments {
            get {
                return ResourceManager.GetString("attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string basicInformation {
            get {
                return ResourceManager.GetString("basicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This work order is cancelled.
        /// </summary>
        internal static string canceledWorkOrder {
            get {
                return ResourceManager.GetString("canceledWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Work order.
        /// </summary>
        internal static string cancelWorkOrder {
            get {
                return ResourceManager.GetString("cancelWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add maintenance type.
        /// </summary>
        internal static string clickHereToAddMaintType {
            get {
                return ResourceManager.GetString("clickHereToAddMaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to select equipment or functional location.
        /// </summary>
        internal static string clickHereToSelectEquipmentOrFlocation {
            get {
                return ResourceManager.GetString("clickHereToSelectEquipmentOrFlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view maintenance types.
        /// </summary>
        internal static string clickHereToViewMaintTypes {
            get {
                return ResourceManager.GetString("clickHereToViewMaintTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Search Criteria.
        /// </summary>
        internal static string defineSearchCriteria {
            get {
                return ResourceManager.GetString("defineSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to enter remark.
        /// </summary>
        internal static string enableToEnterRemark {
            get {
                return ResourceManager.GetString("enableToEnterRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to take Picture.
        /// </summary>
        internal static string enableToTakePicture {
            get {
                return ResourceManager.GetString("enableToTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Equipment .
        /// </summary>
        internal static string equipmentInformation {
            get {
                return ResourceManager.GetString("equipmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        internal static string equipmentType {
            get {
                return ResourceManager.GetString("equipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        internal static string estimatedTime {
            get {
                return ResourceManager.GetString("estimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time(mins).
        /// </summary>
        internal static string estimatedTimeMin {
            get {
                return ResourceManager.GetString("estimatedTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &amp; Images.
        /// </summary>
        internal static string fileAndImageUpload {
            get {
                return ResourceManager.GetString("fileAndImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func. Loc..
        /// </summary>
        internal static string fLocation {
            get {
                return ResourceManager.GetString("fLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Func. Loc..
        /// </summary>
        internal static string fLocationInformation {
            get {
                return ResourceManager.GetString("fLocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func. Loc. / Equip..
        /// </summary>
        internal static string fLocationOrEquipment {
            get {
                return ResourceManager.GetString("fLocationOrEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Instructions from SOP.
        /// </summary>
        internal static string importInstructionFromSOP {
            get {
                return ResourceManager.GetString("importInstructionFromSOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mandatory.
        /// </summary>
        internal static string isMandatory {
            get {
                return ResourceManager.GetString("isMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Equipments.
        /// </summary>
        internal static string listOfEquipment {
            get {
                return ResourceManager.GetString("listOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Func. Loc..
        /// </summary>
        internal static string listofFLocation {
            get {
                return ResourceManager.GetString("listofFLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Maintenance Types.
        /// </summary>
        internal static string listofMaintTypes {
            get {
                return ResourceManager.GetString("listofMaintTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Type Code.
        /// </summary>
        internal static string maintenanceCode {
            get {
                return ResourceManager.GetString("maintenanceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Information.
        /// </summary>
        internal static string maintenanceInfo {
            get {
                return ResourceManager.GetString("maintenanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Name.
        /// </summary>
        internal static string maintenanceName {
            get {
                return ResourceManager.GetString("maintenanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Type.
        /// </summary>
        internal static string maintenanceType {
            get {
                return ResourceManager.GetString("maintenanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Types Information.
        /// </summary>
        internal static string maintTypeInformation {
            get {
                return ResourceManager.GetString("maintTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Code And Description.
        /// </summary>
        internal static string materialCodeAndDesc {
            get {
                return ResourceManager.GetString("materialCodeAndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SOP Selected.
        /// </summary>
        internal static string noTaskGroupSelected {
            get {
                return ResourceManager.GetString("noTaskGroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are creating/editing work order for the below notification:.
        /// </summary>
        internal static string notifiactionBasicInformation {
            get {
                return ResourceManager.GetString("notifiactionBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification By.
        /// </summary>
        internal static string notificationBy {
            get {
                return ResourceManager.GetString("notificationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string notificationCreatedOn {
            get {
                return ResourceManager.GetString("notificationCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string notificationDescription {
            get {
                return ResourceManager.GetString("notificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment/FL Name.
        /// </summary>
        internal static string notificationEquipmentOrLocation {
            get {
                return ResourceManager.GetString("notificationEquipmentOrLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Name.
        /// </summary>
        internal static string notificationName {
            get {
                return ResourceManager.GetString("notificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string notificationPriority {
            get {
                return ResourceManager.GetString("notificationPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type.
        /// </summary>
        internal static string notificationType {
            get {
                return ResourceManager.GetString("notificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        internal static string parameterName {
            get {
                return ResourceManager.GetString("parameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Type.
        /// </summary>
        internal static string parameterType {
            get {
                return ResourceManager.GetString("parameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please save after any modification.
        /// </summary>
        internal static string pleaseSaveAfterModification {
            get {
                return ResourceManager.GetString("pleaseSaveAfterModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE.
        /// </summary>
        internal static string ppe {
            get {
                return ResourceManager.GetString("ppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE Images.
        /// </summary>
        internal static string ppeImages {
            get {
                return ResourceManager.GetString("ppeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE not found.
        /// </summary>
        internal static string ppeNotFound {
            get {
                return ResourceManager.GetString("ppeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string release {
            get {
                return ResourceManager.GetString("release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Instruction.
        /// </summary>
        internal static string safetyInstruction {
            get {
                return ResourceManager.GetString("safetyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Date.
        /// </summary>
        internal static string scheduleDate {
            get {
                return ResourceManager.GetString("scheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        internal static string scheduling {
            get {
                return ResourceManager.GetString("scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please search to load more SOP.
        /// </summary>
        internal static string searchToLoadMoreTaskGroup {
            get {
                return ResourceManager.GetString("searchToLoadMoreTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string selectEquipment {
            get {
                return ResourceManager.GetString("selectEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func. Loc..
        /// </summary>
        internal static string selectFLocation {
            get {
                return ResourceManager.GetString("selectFLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Code.
        /// </summary>
        internal static string selectionCode {
            get {
                return ResourceManager.GetString("selectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SOP.
        /// </summary>
        internal static string selectTaskGroup {
            get {
                return ResourceManager.GetString("selectTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select work group).
        /// </summary>
        internal static string selectWorkGroup {
            get {
                return ResourceManager.GetString("selectWorkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Short Text).
        /// </summary>
        internal static string shortText {
            get {
                return ResourceManager.GetString("shortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowAll.
        /// </summary>
        internal static string showAll {
            get {
                return ResourceManager.GetString("showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Task Details.
        /// </summary>
        internal static string showTaskDetails {
            get {
                return ResourceManager.GetString("showTaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare Parts.
        /// </summary>
        internal static string spareParts {
            get {
                return ResourceManager.GetString("spareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Name.
        /// </summary>
        internal static string taskGroup {
            get {
                return ResourceManager.GetString("taskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Type.
        /// </summary>
        internal static string taskGroupType {
            get {
                return ResourceManager.GetString("taskGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        internal static string taskName {
            get {
                return ResourceManager.GetString("taskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Images.
        /// </summary>
        internal static string toolsImages {
            get {
                return ResourceManager.GetString("toolsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Not Found.
        /// </summary>
        internal static string toolsNotFound {
            get {
                return ResourceManager.GetString("toolsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        internal static string uom {
            get {
                return ResourceManager.GetString("uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Instruction.
        /// </summary>
        internal static string workInstruction {
            get {
                return ResourceManager.GetString("workInstruction", resourceCulture);
            }
        }
    }
}
