//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManageNotification_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageNotification_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ManageNotification_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachments.
        /// </summary>
        internal static string addAttachments {
            get {
                return ResourceManager.GetString("addAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Notification.
        /// </summary>
        internal static string addEditNotificationInfo {
            get {
                return ResourceManager.GetString("addEditNotificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Notification Type.
        /// </summary>
        internal static string addEditNotificationType {
            get {
                return ResourceManager.GetString("addEditNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add notification type.
        /// </summary>
        internal static string clickHereToAddNotificationType {
            get {
                return ResourceManager.GetString("clickHereToAddNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to select equipment or functional location.
        /// </summary>
        internal static string clickHereToSelectEquipmentOrFlocation {
            get {
                return ResourceManager.GetString("clickHereToSelectEquipmentOrFlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view notification types.
        /// </summary>
        internal static string clickHereToViewNotificationTypes {
            get {
                return ResourceManager.GetString("clickHereToViewNotificationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string createdOn {
            get {
                return ResourceManager.GetString("createdOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Work Order.
        /// </summary>
        internal static string createWorkOrder {
            get {
                return ResourceManager.GetString("createWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Search Criteria.
        /// </summary>
        internal static string defineSearchCriteria {
            get {
                return ResourceManager.GetString("defineSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to select equipment .
        /// </summary>
        internal static string doubleClickToSelectEquipment {
            get {
                return ResourceManager.GetString("doubleClickToSelectEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to select functional location.
        /// </summary>
        internal static string doubleClickToSelectFLocation {
            get {
                return ResourceManager.GetString("doubleClickToSelectFLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download And Upload.
        /// </summary>
        internal static string downloadAndUpload {
            get {
                return ResourceManager.GetString("downloadAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Excel.
        /// </summary>
        internal static string downloadExcel {
            get {
                return ResourceManager.GetString("downloadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        internal static string downloadTemplate {
            get {
                return ResourceManager.GetString("downloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Equipment.
        /// </summary>
        internal static string equipmentInformation {
            get {
                return ResourceManager.GetString("equipmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        internal static string equipmentType {
            get {
                return ResourceManager.GetString("equipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.Location.
        /// </summary>
        internal static string fLocation {
            get {
                return ResourceManager.GetString("fLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Functional Location.
        /// </summary>
        internal static string fLocationInformation {
            get {
                return ResourceManager.GetString("fLocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.Location / Equipment.
        /// </summary>
        internal static string fLocationOrEquipment {
            get {
                return ResourceManager.GetString("fLocationOrEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Notifications.
        /// </summary>
        internal static string listOfNotification {
            get {
                return ResourceManager.GetString("listOfNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Notification Types.
        /// </summary>
        internal static string listofNotificationTypes {
            get {
                return ResourceManager.GetString("listofNotificationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Name.
        /// </summary>
        internal static string notificationName {
            get {
                return ResourceManager.GetString("notificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type.
        /// </summary>
        internal static string notificationType {
            get {
                return ResourceManager.GetString("notificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type Code.
        /// </summary>
        internal static string notificationTypeCode {
            get {
                return ResourceManager.GetString("notificationTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type Information.
        /// </summary>
        internal static string notificationTypeInformation {
            get {
                return ResourceManager.GetString("notificationTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        internal static string rejectReason {
            get {
                return ResourceManager.GetString("rejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Notification.
        /// </summary>
        internal static string searchNotification {
            get {
                return ResourceManager.GetString("searchNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowAll.
        /// </summary>
        internal static string showAll {
            get {
                return ResourceManager.GetString("showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Name.
        /// </summary>
        internal static string sortByName {
            get {
                return ResourceManager.GetString("sortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Notification Info.
        /// </summary>
        internal static string uploadNotificationInfo {
            get {
                return ResourceManager.GetString("uploadNotificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        internal static string workOrderNumber {
            get {
                return ResourceManager.GetString("workOrderNumber", resourceCulture);
            }
        }
    }
}
