//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeasurementDocument_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeasurementDocument_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MeasurementDocument_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basic Information.
        /// </summary>
        internal static string addBasicInformation {
            get {
                return ResourceManager.GetString("addBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Measuring Points.
        /// </summary>
        internal static string availableMeasuringPoints {
            get {
                return ResourceManager.GetString("availableMeasuringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string basicInformation {
            get {
                return ResourceManager.GetString("basicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check List Name.
        /// </summary>
        internal static string checkListName {
            get {
                return ResourceManager.GetString("checkListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Search Criteria.
        /// </summary>
        internal static string defineSearchCriteria {
            get {
                return ResourceManager.GetString("defineSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Available Measuring Points.
        /// </summary>
        internal static string listOfAailMeasPoint {
            get {
                return ResourceManager.GetString("listOfAailMeasPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Check Lists.
        /// </summary>
        internal static string listOfMeasurementDocument {
            get {
                return ResourceManager.GetString("listOfMeasurementDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Selected Measuring Points.
        /// </summary>
        internal static string listOfSelectedMeasPoint {
            get {
                return ResourceManager.GetString("listOfSelectedMeasPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Work Orders.
        /// </summary>
        internal static string listOfWorkOrders {
            get {
                return ResourceManager.GetString("listOfWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check List.
        /// </summary>
        internal static string measurementDocument {
            get {
                return ResourceManager.GetString("measurementDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Pt..
        /// </summary>
        internal static string measuringPoint {
            get {
                return ResourceManager.GetString("measuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Points.
        /// </summary>
        internal static string measuringPointsList {
            get {
                return ResourceManager.GetString("measuringPointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Check List.
        /// </summary>
        internal static string newMeasDocument {
            get {
                return ResourceManager.GetString("newMeasDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Date.
        /// </summary>
        internal static string plannedDate {
            get {
                return ResourceManager.GetString("plannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string release {
            get {
                return ResourceManager.GetString("release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Date.
        /// </summary>
        internal static string scheduleDate {
            get {
                return ResourceManager.GetString("scheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        internal static string scheduling {
            get {
                return ResourceManager.GetString("scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Measuring Points.
        /// </summary>
        internal static string selectedMeasuringPoints {
            get {
                return ResourceManager.GetString("selectedMeasuringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select work group).
        /// </summary>
        internal static string selectWorkGgroup {
            get {
                return ResourceManager.GetString("selectWorkGgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string showAll {
            get {
                return ResourceManager.GetString("showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        internal static string workGroup {
            get {
                return ResourceManager.GetString("workGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        internal static string workOrder {
            get {
                return ResourceManager.GetString("workOrder", resourceCulture);
            }
        }
    }
}
