//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeasuringPoint_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeasuringPoint_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MeasuringPoint_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Measuring Point Info.
        /// </summary>
        internal static string addEditMeasuringPoint {
            get {
                return ResourceManager.GetString("addEditMeasuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string addItem {
            get {
                return ResourceManager.GetString("addItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Space.
        /// </summary>
        internal static string addressSpace {
            get {
                return ResourceManager.GetString("addressSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/View Functional Location.
        /// </summary>
        internal static string addViewFunctionalLocation {
            get {
                return ResourceManager.GetString("addViewFunctionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Code.
        /// </summary>
        internal static string clearCode {
            get {
                return ResourceManager.GetString("clearCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Tag.
        /// </summary>
        internal static string connectTag {
            get {
                return ResourceManager.GetString("connectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Places.
        /// </summary>
        internal static string decimalPlaces {
            get {
                return ResourceManager.GetString("decimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Search Criteria.
        /// </summary>
        internal static string defineSearchCriteria {
            get {
                return ResourceManager.GetString("defineSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Excel.
        /// </summary>
        internal static string dowlaodExcel {
            get {
                return ResourceManager.GetString("dowlaodExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downlaod &amp; Upload.
        /// </summary>
        internal static string downlaodAndUpload {
            get {
                return ResourceManager.GetString("downlaodAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download QR Code.
        /// </summary>
        internal static string downloadQRCode {
            get {
                return ResourceManager.GetString("downloadQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        internal static string downloadTemplate {
            get {
                return ResourceManager.GetString("downloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Model.
        /// </summary>
        internal static string equipmentModel {
            get {
                return ResourceManager.GetString("equipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Location.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code.
        /// </summary>
        internal static string generateCode {
            get {
                return ResourceManager.GetString("generateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal Value.
        /// </summary>
        internal static string idealValues {
            get {
                return ResourceManager.GetString("idealValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload below 5 MB file only.
        /// </summary>
        internal static string imageUploadInstruction {
            get {
                return ResourceManager.GetString("imageUploadInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Counter.
        /// </summary>
        internal static string isCounter {
            get {
                return ResourceManager.GetString("isCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string itemName {
            get {
                return ResourceManager.GetString("itemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string limit {
            get {
                return ResourceManager.GetString("limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Warning.
        /// </summary>
        internal static string limitWarning {
            get {
                return ResourceManager.GetString("limitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Measuring Points .
        /// </summary>
        internal static string listOfMeasuringPoints {
            get {
                return ResourceManager.GetString("listOfMeasuringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower.
        /// </summary>
        internal static string lower {
            get {
                return ResourceManager.GetString("lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Limit.
        /// </summary>
        internal static string lowerLimit {
            get {
                return ResourceManager.GetString("lowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Limit (warning).
        /// </summary>
        internal static string lowerLimitWarning {
            get {
                return ResourceManager.GetString("lowerLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string maintenanceTypeDesc {
            get {
                return ResourceManager.GetString("maintenanceTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length.
        /// </summary>
        internal static string maximumLength {
            get {
                return ResourceManager.GetString("maximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Code.
        /// </summary>
        internal static string measuringCode {
            get {
                return ResourceManager.GetString("measuringCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point.
        /// </summary>
        internal static string measuringPoint {
            get {
                return ResourceManager.GetString("measuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        internal static string measuringPointAttribute {
            get {
                return ResourceManager.GetString("measuringPointAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Name.
        /// </summary>
        internal static string measuringPointName {
            get {
                return ResourceManager.GetString("measuringPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Type.
        /// </summary>
        internal static string measuringPointType {
            get {
                return ResourceManager.GetString("measuringPointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Reading Type.
        /// </summary>
        internal static string mpReadingType {
            get {
                return ResourceManager.GetString("mpReadingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opc Details.
        /// </summary>
        internal static string opcDetails {
            get {
                return ResourceManager.GetString("opcDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string quality {
            get {
                return ResourceManager.GetString("quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Add More.
        /// </summary>
        internal static string saveAndAddMore {
            get {
                return ResourceManager.GetString("saveAndAddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Measuring Point.
        /// </summary>
        internal static string searchMeasuringPoint {
            get {
                return ResourceManager.GetString("searchMeasuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Group.
        /// </summary>
        internal static string selectionGroup {
            get {
                return ResourceManager.GetString("selectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Attributes.
        /// </summary>
        internal static string sensorType {
            get {
                return ResourceManager.GetString("sensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string showAll {
            get {
                return ResourceManager.GetString("showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        internal static string sortByName {
            get {
                return ResourceManager.GetString("sortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp.
        /// </summary>
        internal static string timestamp {
            get {
                return ResourceManager.GetString("timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Measuring Point.
        /// </summary>
        internal static string uplaodMeasuringPoint {
            get {
                return ResourceManager.GetString("uplaodMeasuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper.
        /// </summary>
        internal static string upper {
            get {
                return ResourceManager.GetString("upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Limit.
        /// </summary>
        internal static string upperLimit {
            get {
                return ResourceManager.GetString("upperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Limit (warning).
        /// </summary>
        internal static string upperLimitWarning {
            get {
                return ResourceManager.GetString("upperLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
    }
}
