//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SparePartsInfo_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SparePartsInfo_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SparePartsInfo_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Upload.
        /// </summary>
        internal static string downloadAndupload {
            get {
                return ResourceManager.GetString("downloadAndupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Spare Parts.
        /// </summary>
        internal static string downloadInfo {
            get {
                return ResourceManager.GetString("downloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        internal static string downloadTemplate {
            get {
                return ResourceManager.GetString("downloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Spare Parts.
        /// </summary>
        internal static string listOfSpareParts {
            get {
                return ResourceManager.GetString("listOfSpareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAINT_SPARE_PARTS.
        /// </summary>
        internal static string sparePartsFeatureName {
            get {
                return ResourceManager.GetString("sparePartsFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Spare Parts.
        /// </summary>
        internal static string uploadInfo {
            get {
                return ResourceManager.GetString("uploadInfo", resourceCulture);
            }
        }
    }
}
