//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskGroup_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskGroup_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TaskGroup_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit SOP.
        /// </summary>
        internal static string addEditTaskGroup {
            get {
                return ResourceManager.GetString("addEditTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit SOP Type.
        /// </summary>
        internal static string addEditTaskGroupType {
            get {
                return ResourceManager.GetString("addEditTaskGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string addItem {
            get {
                return ResourceManager.GetString("addItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Add More ].
        /// </summary>
        internal static string addMore {
            get {
                return ResourceManager.GetString("addMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string addTask {
            get {
                return ResourceManager.GetString("addTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on ‘Save’ after making any changes.
        /// </summary>
        internal static string changesWontSaveMsg {
            get {
                return ResourceManager.GetString("changesWontSaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Search Criteria.
        /// </summary>
        internal static string defineSearchCriteria {
            get {
                return ResourceManager.GetString("defineSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Upload.
        /// </summary>
        internal static string downloadAndupload {
            get {
                return ResourceManager.GetString("downloadAndupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download SOP.
        /// </summary>
        internal static string downloadTaskGroup {
            get {
                return ResourceManager.GetString("downloadTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to enter remark.
        /// </summary>
        internal static string enableToEnterRemark {
            get {
                return ResourceManager.GetString("enableToEnterRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to take picture.
        /// </summary>
        internal static string enableToTakePicture {
            get {
                return ResourceManager.GetString("enableToTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        internal static string estimatedTime {
            get {
                return ResourceManager.GetString("estimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load sop information.
        /// </summary>
        internal static string failedToLoadSOPInfo {
            get {
                return ResourceManager.GetString("failedToLoadSOPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKGROUP.
        /// </summary>
        internal static string FEATURE_TASKGROUP {
            get {
                return ResourceManager.GetString("FEATURE_TASKGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &amp; Images.
        /// </summary>
        internal static string fileAndImageUpload {
            get {
                return ResourceManager.GetString("fileAndImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image upload.
        /// </summary>
        internal static string imageUpload {
            get {
                return ResourceManager.GetString("imageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mandatory.
        /// </summary>
        internal static string isMandatory {
            get {
                return ResourceManager.GetString("isMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string itemName {
            get {
                return ResourceManager.GetString("itemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of SOP.
        /// </summary>
        internal static string listOfTaskGroup {
            get {
                return ResourceManager.GetString("listOfTaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        internal static string parameterName {
            get {
                return ResourceManager.GetString("parameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Parameters.
        /// </summary>
        internal static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Type.
        /// </summary>
        internal static string parameterType {
            get {
                return ResourceManager.GetString("parameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE.
        /// </summary>
        internal static string ppe {
            get {
                return ResourceManager.GetString("ppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE Images.
        /// </summary>
        internal static string ppeImages {
            get {
                return ResourceManager.GetString("ppeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE not found.
        /// </summary>
        internal static string ppeNotFound {
            get {
                return ResourceManager.GetString("ppeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Action.
        /// </summary>
        internal static string recordAction {
            get {
                return ResourceManager.GetString("recordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Instruction.
        /// </summary>
        internal static string safetyInstruction {
            get {
                return ResourceManager.GetString("safetyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Code.
        /// </summary>
        internal static string selectionCode {
            get {
                return ResourceManager.GetString("selectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string showAll {
            get {
                return ResourceManager.GetString("showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Information.
        /// </summary>
        internal static string taskGroupInformation {
            get {
                return ResourceManager.GetString("taskGroupInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Name.
        /// </summary>
        internal static string taskGroupName {
            get {
                return ResourceManager.GetString("taskGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Type.
        /// </summary>
        internal static string taskGroupType {
            get {
                return ResourceManager.GetString("taskGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        internal static string taskName {
            get {
                return ResourceManager.GetString("taskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Images.
        /// </summary>
        internal static string toolsImages {
            get {
                return ResourceManager.GetString("toolsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Not Found.
        /// </summary>
        internal static string toolsNotFound {
            get {
                return ResourceManager.GetString("toolsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload SOP.
        /// </summary>
        internal static string uploadTaskGroup {
            get {
                return ResourceManager.GetString("uploadTaskGroup", resourceCulture);
            }
        }
    }
}
