//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewWorkOrderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewWorkOrderResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ViewWorkOrderResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual End Date.
        /// </summary>
        internal static string actualEndDate {
            get {
                return ResourceManager.GetString("actualEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Start Date.
        /// </summary>
        internal static string actualStartDate {
            get {
                return ResourceManager.GetString("actualStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Time (Min).
        /// </summary>
        internal static string actualTime {
            get {
                return ResourceManager.GetString("actualTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        internal static string assignedTo {
            get {
                return ResourceManager.GetString("assignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        internal static string capture {
            get {
                return ResourceManager.GetString("capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        internal static string completeDate {
            get {
                return ResourceManager.GetString("completeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string equipmentClass {
            get {
                return ResourceManager.GetString("equipmentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Details.
        /// </summary>
        internal static string equipmentDetails {
            get {
                return ResourceManager.GetString("equipmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        internal static string equipmentName {
            get {
                return ResourceManager.GetString("equipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        internal static string equipmentType {
            get {
                return ResourceManager.GetString("equipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time (Min).
        /// </summary>
        internal static string estimatedTime {
            get {
                return ResourceManager.GetString("estimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From :.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Date.
        /// </summary>
        internal static string installDate {
            get {
                return ResourceManager.GetString("installDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance History.
        /// </summary>
        internal static string maintenanceHistory {
            get {
                return ResourceManager.GetString("maintenanceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Name.
        /// </summary>
        internal static string maintenanceName {
            get {
                return ResourceManager.GetString("maintenanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Type.
        /// </summary>
        internal static string maintenanceType {
            get {
                return ResourceManager.GetString("maintenanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.Name.
        /// </summary>
        internal static string maintName {
            get {
                return ResourceManager.GetString("maintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuals.
        /// </summary>
        internal static string manuals {
            get {
                return ResourceManager.GetString("manuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Code And Description.
        /// </summary>
        internal static string materialCodeAndDesc {
            get {
                return ResourceManager.GetString("materialCodeAndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point List.
        /// </summary>
        internal static string measuringPointList {
            get {
                return ResourceManager.GetString("measuringPointList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name.
        /// </summary>
        internal static string modelName {
            get {
                return ResourceManager.GetString("modelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string modelNumber {
            get {
                return ResourceManager.GetString("modelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP Reading History.
        /// </summary>
        internal static string mpReadingHistory {
            get {
                return ResourceManager.GetString("mpReadingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string noRecordFound {
            get {
                return ResourceManager.GetString("noRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        internal static string parameterName {
            get {
                return ResourceManager.GetString("parameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos &amp; Videos.
        /// </summary>
        internal static string photosAndVideos {
            get {
                return ResourceManager.GetString("photosAndVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE.
        /// </summary>
        internal static string ppe {
            get {
                return ResourceManager.GetString("ppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased Date.
        /// </summary>
        internal static string purchaseDate {
            get {
                return ResourceManager.GetString("purchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported To.
        /// </summary>
        internal static string reportedTo {
            get {
                return ResourceManager.GetString("reportedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Quantity.
        /// </summary>
        internal static string requiredQuantity {
            get {
                return ResourceManager.GetString("requiredQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Instruction.
        /// </summary>
        internal static string safetyInstruction {
            get {
                return ResourceManager.GetString("safetyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Date.
        /// </summary>
        internal static string scheduledDate {
            get {
                return ResourceManager.GetString("scheduledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string serialNumber {
            get {
                return ResourceManager.GetString("serialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string showAll {
            get {
                return ResourceManager.GetString("showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare parts.
        /// </summary>
        internal static string spareParts {
            get {
                return ResourceManager.GetString("spareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Documents.
        /// </summary>
        internal static string specificationDocuments {
            get {
                return ResourceManager.GetString("specificationDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started By.
        /// </summary>
        internal static string startedBy {
            get {
                return ResourceManager.GetString("startedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Task.
        /// </summary>
        internal static string startTask {
            get {
                return ResourceManager.GetString("startTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Group Is Not Found.
        /// </summary>
        internal static string taskGroupNotFound {
            get {
                return ResourceManager.GetString("taskGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To :.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        internal static string uom {
            get {
                return ResourceManager.GetString("uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Quantity.
        /// </summary>
        internal static string usedQuantity {
            get {
                return ResourceManager.GetString("usedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Expiry.
        /// </summary>
        internal static string warrentyExpiry {
            get {
                return ResourceManager.GetString("warrentyExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Number.
        /// </summary>
        internal static string warrentyNumber {
            get {
                return ResourceManager.GetString("warrentyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Status.
        /// </summary>
        internal static string warrentyStatus {
            get {
                return ResourceManager.GetString("warrentyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Instructions.
        /// </summary>
        internal static string workInstructions {
            get {
                return ResourceManager.GetString("workInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        internal static string workOrder {
            get {
                return ResourceManager.GetString("workOrder", resourceCulture);
            }
        }
    }
}
