var languageResource = {};
languageResource.resMsg_Error = "Error: ";
languageResource.resMsg_AlreadyExistsWorkGroupName = "Work group name already exist";
languageResource.resMsg_SuccessfullyInsertedWorkGroupInfo = "Successfully inserted work group information";
languageResource.resMsg_SuccessfullyUpdatedWorkGroupInfo = "Successfully updated work group information";
languageResource.resMsg_CanNotUpdatedAlreadyExistInInActiveState = "Work group info already exist in inactive state and can't be updated";
languageResource.resMsg_FailedAddOrUpdateWorkGroupInfo = "Failed to add/update work group information";
languageResource.resMsg_SaveandAddMore = "Save & Add More";
languageResource.resMsg_Update = "Update";
languageResource.resMsg_BtnConfirm = "Confirm";
languageResource.resMsg_BtnCancel = "Cancel";
languageResource.resMsg_BtnOK = "Ok";
languageResource.resMsg_FailedToLoadWorkGroup = "Failed to load work group";
languageResource.resMsg_FailedToLoadAutoCompleteForUser ="Failed to load autocomplete for user";
languageResource.resMsg_FailedToLoadWorkGroupInfo = "Failed to load work group information";

languageResource.resMsg_EnterGroupName = "Please enter work group name"; 
languageResource.resMsg_UserAddedBothAssigneeAndReportTo = "Same user name cannot be added to both assignee and report to";
languageResource.resMsg_EnterValidUserName = "Please enter a valid username";
languageResource.resMsg_AlreadyAdded = " already added";
languageResource.resMsg_AtleastOneNotificationEnable = "Atleast one notification should be enabled for ";
languageResource.resMsg_PleaseEnterAtleastOneUser = "Please enter atleast one user for assignee/report to";

languageResource.resMsg_DeleteWorkGroupInfoConfirm = "Are you sure you want to delete work group info?";
languageResource.resMsg_FailedToDeleteWorkGroupInfo = "Failed to delete work group information";
languageResource.resMsg_DeleteWorkGroupUserInfoConfirm = "Are you sure you want to delete this user information?";
languageResource.resMsg_CantDeleteWorkGroupInfo = "Cant delete user information,atleast one record should be present";
languageResource.resMsg_WorkGroupUserInfoDoesnotExist = "User information does not exist in 'active' status";
languageResource.resMsg_FailedToDeleteWorkGroupUserInfo = "Failed to delete work group user information";