//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Equipment_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Equipment_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Equipment_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Item(s).
        /// </summary>
        internal static string addedItems {
            get {
                return ResourceManager.GetString("addedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item(s).
        /// </summary>
        internal static string deletedItems {
            get {
                return ResourceManager.GetString("deletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        internal static string documentName {
            get {
                return ResourceManager.GetString("documentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Attachments Info Upload Log.
        /// </summary>
        internal static string equipmentAttachmentInfoUploadLog {
            get {
                return ResourceManager.GetString("equipmentAttachmentInfoUploadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Info Upload Log.
        /// </summary>
        internal static string equipmentBasicInfoUploadLog {
            get {
                return ResourceManager.GetString("equipmentBasicInfoUploadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string equipmentClass {
            get {
                return ResourceManager.GetString("equipmentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Code.
        /// </summary>
        internal static string equipmentCode {
            get {
                return ResourceManager.GetString("equipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Log Information.
        /// </summary>
        internal static string equipmentLogInformation {
            get {
                return ResourceManager.GetString("equipmentLogInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        internal static string equipmentName {
            get {
                return ResourceManager.GetString("equipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Info Upload Log.
        /// </summary>
        internal static string equipmentSupportInfoUploadLog {
            get {
                return ResourceManager.GetString("equipmentSupportInfoUploadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Resons(s).
        /// </summary>
        internal static string failureResons {
            get {
                return ResourceManager.GetString("failureResons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Name.
        /// </summary>
        internal static string imageName {
            get {
                return ResourceManager.GetString("imageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Date.
        /// </summary>
        internal static string installDate {
            get {
                return ResourceManager.GetString("installDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in line number.
        /// </summary>
        internal static string inTheLineNumber {
            get {
                return ResourceManager.GetString("inTheLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        internal static string lastUpdatedBy {
            get {
                return ResourceManager.GetString("lastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update On.
        /// </summary>
        internal static string lastUpdatedOn {
            get {
                return ResourceManager.GetString("lastUpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link To Resource.
        /// </summary>
        internal static string linkToResource {
            get {
                return ResourceManager.GetString("linkToResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuals.
        /// </summary>
        internal static string manuals {
            get {
                return ResourceManager.GetString("manuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Name.
        /// </summary>
        internal static string manufacturerName {
            get {
                return ResourceManager.GetString("manufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string modelNumber {
            get {
                return ResourceManager.GetString("modelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Equipment is part of.
        /// </summary>
        internal static string parentEquipment {
            get {
                return ResourceManager.GetString("parentEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos &amp; Videos.
        /// </summary>
        internal static string photosAndVideos {
            get {
                return ResourceManager.GetString("photosAndVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        internal static string purchaseDate {
            get {
                return ResourceManager.GetString("purchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer From Model .
        /// </summary>
        internal static string referFromModel {
            get {
                return ResourceManager.GetString("referFromModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serail Number.
        /// </summary>
        internal static string serailNumber {
            get {
                return ResourceManager.GetString("serailNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Documents.
        /// </summary>
        internal static string specificationDocument {
            get {
                return ResourceManager.GetString("specificationDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted.
        /// </summary>
        internal static string successfullyDeleted {
            get {
                return ResourceManager.GetString("successfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Inserted.
        /// </summary>
        internal static string successfullyInserted {
            get {
                return ResourceManager.GetString("successfullyInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Updated.
        /// </summary>
        internal static string successfullyUpdated {
            get {
                return ResourceManager.GetString("successfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Email ID.
        /// </summary>
        internal static string supportEmailID {
            get {
                return ResourceManager.GetString("supportEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Name.
        /// </summary>
        internal static string supportName {
            get {
                return ResourceManager.GetString("supportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Number.
        /// </summary>
        internal static string supportNumber {
            get {
                return ResourceManager.GetString("supportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Type.
        /// </summary>
        internal static string supportType {
            get {
                return ResourceManager.GetString("supportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Item(s).
        /// </summary>
        internal static string updatedItems {
            get {
                return ResourceManager.GetString("updatedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep equipment images and attached document files inside EquipmentAttachments folder.
        ///and keep measuring point images inside MeasuringPoint folder. Refer the images and attached document file name in excel templates in the respective equipment and measuring point..
        /// </summary>
        internal static string uploadReadme {
            get {
                return ResourceManager.GetString("uploadReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Expire Date.
        /// </summary>
        internal static string warrantyExpireDate {
            get {
                return ResourceManager.GetString("warrantyExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Number.
        /// </summary>
        internal static string warrantyNumber {
            get {
                return ResourceManager.GetString("warrantyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Start Date.
        /// </summary>
        internal static string warrantyStartDate {
            get {
                return ResourceManager.GetString("warrantyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkGroup.
        /// </summary>
        internal static string workGroup {
            get {
                return ResourceManager.GetString("workGroup", resourceCulture);
            }
        }
    }
}
