//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Maintenance_LogInformations_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Maintenance_LogInformations_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Maintenance_LogInformations_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted document : [XXX] for equipment name : [YYY].
        /// </summary>
        internal static string documentEquipmentAdded {
            get {
                return ResourceManager.GetString("documentEquipmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted document : [XXX] for equipment model name : [YYY].
        /// </summary>
        internal static string documentEquipmentModelAdded {
            get {
                return ResourceManager.GetString("documentEquipmentModelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted document : [XXX].
        /// </summary>
        internal static string documentInfoDeleted {
            get {
                return ResourceManager.GetString("documentInfoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted information for equipment name : [XXX] and equipment code : [YYY].
        /// </summary>
        internal static string equipmentInfoAdded {
            get {
                return ResourceManager.GetString("equipmentInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted information for equipment name : [XXX] and equipment code : [YYY] through excel.
        /// </summary>
        internal static string equipmentInfoAddedExcel {
            get {
                return ResourceManager.GetString("equipmentInfoAddedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted information for equipment name : [XXX] and equipment code : [YYY].
        /// </summary>
        internal static string equipmentInfoDeleted {
            get {
                return ResourceManager.GetString("equipmentInfoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted information for equipment name : [XXX] and equipment code : [YYY] through excel.
        /// </summary>
        internal static string equipmentInfoDeletedExcel {
            get {
                return ResourceManager.GetString("equipmentInfoDeletedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated information for equipment name : [XXX] and equipment code : [YYY].
        /// </summary>
        internal static string equipmentInfoUpdated {
            get {
                return ResourceManager.GetString("equipmentInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated information for equipment name : [XXX] and equipment code : [YYY] through excel.
        /// </summary>
        internal static string equipmentInfoUpdatedExcel {
            get {
                return ResourceManager.GetString("equipmentInfoUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status active for equipment name : [XXX] and equipment code : [YYY].
        /// </summary>
        internal static string equipmentLocationStatus {
            get {
                return ResourceManager.GetString("equipmentLocationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted information for equipment model name : [XXX].
        /// </summary>
        internal static string equipmentModelInfoAdded {
            get {
                return ResourceManager.GetString("equipmentModelInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted information for equipment model name : [XXX].
        /// </summary>
        internal static string equipmentModelInfoDeleted {
            get {
                return ResourceManager.GetString("equipmentModelInfoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status active for equipment model name : [XXX].
        /// </summary>
        internal static string equipmentModelInfoStatus {
            get {
                return ResourceManager.GetString("equipmentModelInfoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated information for equipment model name : [XXX].
        /// </summary>
        internal static string equipmentModelInfoUpdated {
            get {
                return ResourceManager.GetString("equipmentModelInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status active for equipment name : [XXX] and equipment code : [YYY] through excel.
        /// </summary>
        internal static string equipmentStatusExcel {
            get {
                return ResourceManager.GetString("equipmentStatusExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted functional location information : [XXX] through excel.
        /// </summary>
        internal static string funcationalLocationDeletedExcel {
            get {
                return ResourceManager.GetString("funcationalLocationDeletedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted information for functional location name : [XXX].
        /// </summary>
        internal static string functionalLocationInfoAdded {
            get {
                return ResourceManager.GetString("functionalLocationInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted information for functional location name : [XXX] through excel.
        /// </summary>
        internal static string functionalLocationInfoAddedExcel {
            get {
                return ResourceManager.GetString("functionalLocationInfoAddedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted information for functional location name :.
        /// </summary>
        internal static string functionalLocationInfoDeleted {
            get {
                return ResourceManager.GetString("functionalLocationInfoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated information for functional location name : [XXX].
        /// </summary>
        internal static string functionalLocationInfoUpdated {
            get {
                return ResourceManager.GetString("functionalLocationInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated information for functional location name : [XXX] through excel.
        /// </summary>
        internal static string functionalLocationInfoUpdatedExcel {
            get {
                return ResourceManager.GetString("functionalLocationInfoUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status active for functional location name : [XXX].
        /// </summary>
        internal static string functionalLocationStatus {
            get {
                return ResourceManager.GetString("functionalLocationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added information for measuring point name : [XXX].
        /// </summary>
        internal static string measuringPointInfoAdded {
            get {
                return ResourceManager.GetString("measuringPointInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated information for measuring point name : [XXX].
        /// </summary>
        internal static string measuringPointInfoUpdated {
            get {
                return ResourceManager.GetString("measuringPointInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status active for measuring point : [XXX]  .
        /// </summary>
        internal static string measuringPointStatus {
            get {
                return ResourceManager.GetString("measuringPointStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted notification info for schedule ID : [XXX].
        /// </summary>
        internal static string notificationInfoSuccess {
            get {
                return ResourceManager.GetString("notificationInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted reading result info for schedule  ID : [XXX]  , workorder ID : [YYY] and measuring point ID : [ZZZ].
        /// </summary>
        internal static string readingResultInfoSuccess {
            get {
                return ResourceManager.GetString("readingResultInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted support info : [XXX] for equipment name : [YYY] through excel.
        /// </summary>
        internal static string supportInfoDeletedExcel {
            get {
                return ResourceManager.GetString("supportInfoDeletedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted support info : [XXX] for equipment name : [YYY] through excel.
        /// </summary>
        internal static string supportInfoInsertExcel {
            get {
                return ResourceManager.GetString("supportInfoInsertExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated support info : [XXX] for equipment name : [YYY] through excel.
        /// </summary>
        internal static string supportInfoUpdatedExcel {
            get {
                return ResourceManager.GetString("supportInfoUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted tool information for tool descripton : [XXX].
        /// </summary>
        internal static string toolInfoAdded {
            get {
                return ResourceManager.GetString("toolInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted  tool information for tool descripton : [XXX].
        /// </summary>
        internal static string toolInfoDeleted {
            get {
                return ResourceManager.GetString("toolInfoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status active tool description : [XXX].
        /// </summary>
        internal static string toolInfoStatus {
            get {
                return ResourceManager.GetString("toolInfoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated tool information for tool descripton : [XXX].
        /// </summary>
        internal static string toolInfoUpdated {
            get {
                return ResourceManager.GetString("toolInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted information for work group name : [XXX].
        /// </summary>
        internal static string workGroupInfoAdded {
            get {
                return ResourceManager.GetString("workGroupInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted work group : [XXX].
        /// </summary>
        internal static string workGroupInfoDeleted {
            get {
                return ResourceManager.GetString("workGroupInfoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated information for functional location name : [XXX].
        /// </summary>
        internal static string workGroupInfoUpdated {
            get {
                return ResourceManager.GetString("workGroupInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated status active for work group name : [XXX].
        /// </summary>
        internal static string workGroupStatus {
            get {
                return ResourceManager.GetString("workGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted information for user name : [XXX] for work group name : [YYY] through excel.
        /// </summary>
        internal static string workGroupUserDeletedExcel {
            get {
                return ResourceManager.GetString("workGroupUserDeletedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted information for user name : [XXX] for work group name : [YYY].
        /// </summary>
        internal static string workGroupUserInfoDeleted {
            get {
                return ResourceManager.GetString("workGroupUserInfoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted information for user name : [XXX] with [Schedule notification : [YYY]],[On work statement : [ZZZ]] ,[On report : [AAA]],[On downtime : [BBB]] and [On complete : [CCC]] for work group : [DDD] through excel.
        /// </summary>
        internal static string workGroupUserInfoInsertedExcel {
            get {
                return ResourceManager.GetString("workGroupUserInfoInsertedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated on downtime from [AAA] to [BBB] for user name : [XXX] for work group : [YYY] through excel.
        /// </summary>
        internal static string workGroupUserOnCompleteUpdatedExcel {
            get {
                return ResourceManager.GetString("workGroupUserOnCompleteUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated on downtime from [AAA] to [BBB] for user name : [XXX] for work group : [YYY] through excel.
        /// </summary>
        internal static string workGroupUserOnDowntimeUpdatedExcel {
            get {
                return ResourceManager.GetString("workGroupUserOnDowntimeUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated on report  from [AAA] to [BBB] for user name : [XXX] for work group : [YYY] through excel.
        /// </summary>
        internal static string workGroupUserOnReportUpdatedExcel {
            get {
                return ResourceManager.GetString("workGroupUserOnReportUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated on work statement from [AAA] to [BBB] for user name : [XXX] for work group : [YYY] through excel.
        /// </summary>
        internal static string workGroupUserOnWorkUpdatedExcel {
            get {
                return ResourceManager.GetString("workGroupUserOnWorkUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated schedule notification from [AAA] to [BBB] for user name : [XXX] for work group : [YYY] through excel.
        /// </summary>
        internal static string workGroupUserScheduleNotificationUpdatedExcel {
            get {
                return ResourceManager.GetString("workGroupUserScheduleNotificationUpdatedExcel", resourceCulture);
            }
        }
    }
}
