//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeasuringPoint_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeasuringPoint_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MeasuringPoint_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Item(s).
        /// </summary>
        internal static string addedItems {
            get {
                return ResourceManager.GetString("addedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic.
        /// </summary>
        internal static string characteristic {
            get {
                return ResourceManager.GetString("characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Type.
        /// </summary>
        internal static string chooseType {
            get {
                return ResourceManager.GetString("chooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource.
        /// </summary>
        internal static string dataSource {
            get {
                return ResourceManager.GetString("dataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Places.
        /// </summary>
        internal static string decimalPlaces {
            get {
                return ResourceManager.GetString("decimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Item(s).
        /// </summary>
        internal static string deletedItems {
            get {
                return ResourceManager.GetString("deletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        internal static string equipmentName {
            get {
                return ResourceManager.GetString("equipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Reason(s).
        /// </summary>
        internal static string failureResons {
            get {
                return ResourceManager.GetString("failureResons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Location.
        /// </summary>
        internal static string functionalLocation {
            get {
                return ResourceManager.GetString("functionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Service.
        /// </summary>
        internal static string gatewayService {
            get {
                return ResourceManager.GetString("gatewayService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Name.
        /// </summary>
        internal static string imageName {
            get {
                return ResourceManager.GetString("imageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in line number.
        /// </summary>
        internal static string inLineNumber {
            get {
                return ResourceManager.GetString("inLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Counter.
        /// </summary>
        internal static string isCounter {
            get {
                return ResourceManager.GetString("isCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Limit.
        /// </summary>
        internal static string lowerLimit {
            get {
                return ResourceManager.GetString("lowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Limit Warning.
        /// </summary>
        internal static string lowerLimitWarning {
            get {
                return ResourceManager.GetString("lowerLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Text Length.
        /// </summary>
        internal static string maxTextLength {
            get {
                return ResourceManager.GetString("maxTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Name.
        /// </summary>
        internal static string measuringPoint {
            get {
                return ResourceManager.GetString("measuringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Attributes.
        /// </summary>
        internal static string measuringPointAttr {
            get {
                return ResourceManager.GetString("measuringPointAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Basic Info Upload Log.
        /// </summary>
        internal static string measuringPointBasicInfoUploadLog {
            get {
                return ResourceManager.GetString("measuringPointBasicInfoUploadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Code.
        /// </summary>
        internal static string measuringPointCode {
            get {
                return ResourceManager.GetString("measuringPointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted measuring point information for equipment  : [XXX] through excel.
        /// </summary>
        internal static string measuringPointInfoAddedExcel {
            get {
                return ResourceManager.GetString("measuringPointInfoAddedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted measuring point information for equipment   : [XXX] through excel.
        /// </summary>
        internal static string measuringPointInfoDeletedExcel {
            get {
                return ResourceManager.GetString("measuringPointInfoDeletedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated measuring point information for equipment   : [XXX] through excel.
        /// </summary>
        internal static string measuringPointInfoUpdatedExcel {
            get {
                return ResourceManager.GetString("measuringPointInfoUpdatedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Log Information.
        /// </summary>
        internal static string measuringPointLogInfo {
            get {
                return ResourceManager.GetString("measuringPointLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Point Reading Type.
        /// </summary>
        internal static string measuringPointReadingType {
            get {
                return ResourceManager.GetString("measuringPointReadingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP Type.
        /// </summary>
        internal static string mpType {
            get {
                return ResourceManager.GetString("mpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Group.
        /// </summary>
        internal static string selectionGroup {
            get {
                return ResourceManager.GetString("selectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string serverName {
            get {
                return ResourceManager.GetString("serverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted.
        /// </summary>
        internal static string successfullyDeleted {
            get {
                return ResourceManager.GetString("successfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Added.
        /// </summary>
        internal static string successfullyInserted {
            get {
                return ResourceManager.GetString("successfullyInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Updated.
        /// </summary>
        internal static string successfullyUpdated {
            get {
                return ResourceManager.GetString("successfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Name.
        /// </summary>
        internal static string tagName {
            get {
                return ResourceManager.GetString("tagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value.
        /// </summary>
        internal static string targetValue {
            get {
                return ResourceManager.GetString("targetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        internal static string uom {
            get {
                return ResourceManager.GetString("uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Item(s).
        /// </summary>
        internal static string updatedItems {
            get {
                return ResourceManager.GetString("updatedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep images inside folder MeasuringPointImages. Refer images name in the templates against the equipment or functional location. It simply means that image to the equipment or functional location..
        /// </summary>
        internal static string uploadReadme {
            get {
                return ResourceManager.GetString("uploadReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Limit.
        /// </summary>
        internal static string upperLimit {
            get {
                return ResourceManager.GetString("upperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Limit Warning.
        /// </summary>
        internal static string upperLimitWarning {
            get {
                return ResourceManager.GetString("upperLimitWarning", resourceCulture);
            }
        }
    }
}
