//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskGroup_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskGroup_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TaskGroup_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Items.
        /// </summary>
        internal static string addedItems {
            get {
                return ResourceManager.GetString("addedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Items.
        /// </summary>
        internal static string deletedItems {
            get {
                return ResourceManager.GetString("deletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to Enter Remark?.
        /// </summary>
        internal static string enableRemark {
            get {
                return ResourceManager.GetString("enableRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to Take Picture?.
        /// </summary>
        internal static string enableTakePicture {
            get {
                return ResourceManager.GetString("enableTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        internal static string estimatedTime {
            get {
                return ResourceManager.GetString("estimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Reasons.
        /// </summary>
        internal static string failureReasons {
            get {
                return ResourceManager.GetString("failureReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parameter Mandatory?.
        /// </summary>
        internal static string isParameterMandatory {
            get {
                return ResourceManager.GetString("isParameterMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Picture Mandatory?.
        /// </summary>
        internal static string isPictureMandatory {
            get {
                return ResourceManager.GetString("isPictureMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Remark Mandatory?.
        /// </summary>
        internal static string isRemarkMandatory {
            get {
                return ResourceManager.GetString("isRemarkMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Code.
        /// </summary>
        internal static string materialCode {
            get {
                return ResourceManager.GetString("materialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        internal static string parameterName {
            get {
                return ResourceManager.GetString("parameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Type.
        /// </summary>
        internal static string parameterType {
            get {
                return ResourceManager.GetString("parameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE Image Name.
        /// </summary>
        internal static string ppeImageName {
            get {
                return ResourceManager.GetString("ppeImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Instructions.
        /// </summary>
        internal static string safetyInstructions {
            get {
                return ResourceManager.GetString("safetyInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Group Code.
        /// </summary>
        internal static string selectionCode {
            get {
                return ResourceManager.GetString("selectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Separated by comma).
        /// </summary>
        internal static string separatedByComma {
            get {
                return ResourceManager.GetString("separatedByComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Log Information.
        /// </summary>
        internal static string sopLogInfo {
            get {
                return ResourceManager.GetString("sopLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Name.
        /// </summary>
        internal static string sopName {
            get {
                return ResourceManager.GetString("sopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Param Log Information.
        /// </summary>
        internal static string sopParamLogInfo {
            get {
                return ResourceManager.GetString("sopParamLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Spare Parts Log Information.
        /// </summary>
        internal static string sopSparePartsLogInfo {
            get {
                return ResourceManager.GetString("sopSparePartsLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Type.
        /// </summary>
        internal static string sopType {
            get {
                return ResourceManager.GetString("sopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Upload Log Information.
        /// </summary>
        internal static string sopUploadLogInfo {
            get {
                return ResourceManager.GetString("sopUploadLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Sequence.
        /// </summary>
        internal static string stepSequence {
            get {
                return ResourceManager.GetString("stepSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted.
        /// </summary>
        internal static string successfullyDeleted {
            get {
                return ResourceManager.GetString("successfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Inserted.
        /// </summary>
        internal static string successfullyInserted {
            get {
                return ResourceManager.GetString("successfullyInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Updated.
        /// </summary>
        internal static string successfullyUpdated {
            get {
                return ResourceManager.GetString("successfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Description.
        /// </summary>
        internal static string taskDescription {
            get {
                return ResourceManager.GetString("taskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Name.
        /// </summary>
        internal static string taskName {
            get {
                return ResourceManager.GetString("taskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Name .
        /// </summary>
        internal static string toolsImageName {
            get {
                return ResourceManager.GetString("toolsImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        internal static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Items.
        /// </summary>
        internal static string updatedItems {
            get {
                return ResourceManager.GetString("updatedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Folder Reference ID.
        /// </summary>
        internal static string uploadDocumentReference {
            get {
                return ResourceManager.GetString("uploadDocumentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep images or document related to any task inside folder TaskReferenceID_1, TaskReferenceID_2 etc. Rename folder TaskReferenceID_1, TaskReferenceID_2 etc to any number. Refer same number in the templates against the task. It simply means that attach all the documents or images inside the folder to the task referring that folder number..
        /// </summary>
        internal static string uploadReadme {
            get {
                return ResourceManager.GetString("uploadReadme", resourceCulture);
            }
        }
    }
}
